mode: dev
name: bulebell
version: 1.0.0
machine_id: 1
start_time: "2024-01-01"
port: 9999

jwt:
  expire: 3600

mysql:
  hostname: localhost
  port: 3306
  user: root
  password: bendimima
  db: bluebell

redis:
  hostname: localhost
  port: 6379
  user:
  password:
  database: 0

log:
  filename: logfile
  level: info
  max_size: 10
  max_age: 10
  max_backups: 10
